export const GET_LEFT_POSITION = "GET_LEFT_POSITION";
export const GET_RIGHT_POSITION = "GET_RIGHT_POSITION";
export const GET_RIGHT_WEIGHT = "GET_RIGHT_WEIGHT";
export const GET_LEFT_WEIGHT = "GET_LEFT_WEIGHT";
export const GET_HEIGHT = "GET_HEIGHT";
